version: "3.8"

services:
  backend:
    build: ./server
    expose:
      - "3005"
    ports:
      - "3005:3005"
    env_file:
      - .env.server
    networks:
      - app-network

  frontend:
    build: ./client
    expose:
      - "8081"
    ports:
      - "8081:80"
    env_file:
      - .env.client
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
