version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "3004:3004"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=3004
      - JWT_TOKEN_SECRET_KEY=${JWT_TOKEN_SECRET_KEY}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - ENABLE_AI_EVALUATION=${ENABLE_AI_EVALUATION}
      - NUMBER_OF_QUESTIONS_IN_INTERVIEW=${NUMBER_OF_QUESTIONS_IN_INTERVIEW}
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge